version: '2'
services:
    mysql:
        image: mysql:5.7.16
        ports:
        - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: mypassword
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
        - ./mysql_data:/var/lib/mysql
        restart: unless-stopped